x<-read.csv('data/tests/independent.csv');r<-read.csv('data/tests/results.csv')
a<-x$value[x$group=='Q'];b<-x$value[x$group=='Control'];se2<-var(a)/length(a)+var(b)/length(b);df<-se2^2/((var(a)/length(a))^2/(length(a)-1)+(var(b)/length(b))^2/(length(b)-1));est<-mean(a)-mean(b);ci<-est+c(-1,1)*qt(.975,df)*sqrt(se2)
stopifnot(max(abs(ci-unlist(r[1,c('low','high')])))<1e-10,abs(r$p[1]-2*pt(-abs(est/sqrt(se2)),df))<1e-12)
raw<-read.csv('data/simulated/assay_readings.csv');s<-aggregate(activity~preparation+condition,raw,mean);p<-reshape(s,idvar='preparation',timevar='condition',direction='wide');d<-p[['activity.Compound Q']]-p[['activity.Vehicle']];tt<-t.test(d)
stopifnot(abs(mean(d)-r$estimate[2])<1e-10,max(abs(tt$conf.int-unlist(r[2,c('low','high')])))<1e-10,abs(t.test(p[['activity.Compound Q']],p[['activity.Vehicle']],paired=TRUE)$p.value-tt$p.value)<1e-12)
z<-read.csv('data/tests/interaction.csv');z$treatment<-factor(z$treatment,levels=c('Control','Q'));z$genotype<-factor(z$genotype,levels=c('Wild type','Knockout'));fit<-lm(value~treatment*genotype,z);means<-with(z,tapply(value,list(treatment,genotype),mean));contrast<-diff(means[,'Knockout'])-diff(means[,'Wild type']);stopifnot(abs(contrast-coef(fit)[4])<1e-10)
dose<-read.csv('data/tests/dose.csv');stopifnot(all(table(dose$group)==8),abs(anova(lm(value~group,dose))$'F value'[1]-summary(aov(value~group,dose))[[1]]$'F value'[1])<1e-10)
set.seed(20261011);expected<-c(rnorm(8,100,10),rnorm(8,85,17));stopifnot(max(abs(expected-x$value))<1e-10)
cat('All independent, paired, interaction, ANOVA and seed checks passed.\n')
