source('R/simulate_intervals.R');source('R/power_design.R');source('R/summarise_assay.R');source('R/simulate_assay.R')
raw<-read.csv('data/simulated/assay_readings.csv');stopifnot(isTRUE(all.equal(raw,simulate_assay(),check.attributes=FALSE)))
r<-read.csv('data/power/repeated_changes.csv');x<-matrix(r$change,ncol=6,byrow=TRUE);s<-read.csv('data/power/repeated_experiments.csv')
stopifnot(nrow(x)==10000,all(table(r$experiment)==6),max(abs(x-simulate_repeated_assay(seed=20261007L)))<1e-10)
a<-interval_summary(x);p<-2*pt(-abs(a$mean/a$se),5)
stopifnot(max(abs(s$p-p))<1e-12,all(s$reject==(p<.05)),max(abs(s$lower-a$lower))<1e-10,max(abs(s$upper-a$upper))<1e-10)
e<-read.csv('data/power/illustrative_experiments.csv');stopifnot(e$experiment[1]==which(s$reject)[1],e$experiment[2]==which(!s$reject)[1])
sigma<-sqrt(9^2+18+2*2.5^2/3)
analytic<-paired_power(6,14,sigma)
check<-power.t.test(n=6,delta=14,sd=sigma,type='paired',sig.level=.05,alternative='two.sided',strict=TRUE)$power
stopifnot(abs(analytic-check)<1e-10,abs(mean(s$reject)-analytic)<.02,abs(paired_power(6,0,sigma)-.05)<1e-10)
g<-read.csv('data/power/planning_sensitivity.csv')
for(i in seq_len(nrow(g))) stopifnot(paired_power(g$n[i],g$effect[i],g$difference_sd[i])>=.8,paired_power(g$n[i]-1,g$effect[i],g$difference_sd[i])<.8)
precision<-read.csv('data/power/precision.csv');stopifnot(max(abs(precision$se-sigma/sqrt(precision$n)))<1e-12)
d<-read.csv('data/power/design_comparison.csv');unrelated<-d$mean[d$design=='Unrelated preparations'];stopifnot(max(abs(unrelated-simulate_unrelated_means()))<1e-10,abs(sd(unrelated)-sqrt((2*15^2+9^2+18+2*2.5^2/3)/6))<.2)
w<-read.csv('data/power/assay_well_options.csv');stopifnot(abs(w$se[2]^2-(3*(81+18+12.5/4)+3*sigma^2)/36)<1e-12,w$se[3]<w$se[2],w$se[2]<w$se[1])
cat('PASS: unchanged original data; reproducible 10,000 paired experiments; individual CI/p and decision checks; disclosed selection; analytic two-tail power agrees with R; sensitivity Ns minimal integers; precision, design comparison and assay-well variance checks.\n')
