library(ggplot2)
dir.create('data/tests',recursive=TRUE,showWarnings=FALSE)
set.seed(20261011)
ink<-'#172E3B';teal<-'#237A87';rust<-'#B64C2E';paper<-'#FAF8F2'
th<-theme_minimal(base_size=19)+theme(text=element_text(colour=ink),plot.background=element_rect(fill=paper,colour=NA),panel.background=element_rect(fill=paper,colour=NA),panel.grid.minor=element_blank(),legend.position='none')
savefig<-function(g,name,w=11,h=3.5)ggsave(paste0('figures/generated/tests-',name,'.png'),g+th,width=w,height=h,dpi=160,bg=paper)
ind<-data.frame(group=rep(c('Control','Q'),each=8),value=c(rnorm(8,100,10),rnorm(8,85,17)))
write.csv(ind,'data/tests/independent.csv',row.names=FALSE)
wi<-t.test(ind$value[ind$group=='Q'],ind$value[ind$group=='Control'])
g<-ggplot(ind,aes(group,value,colour=group))+geom_point(position=position_jitter(width=.08,seed=11),size=3)+stat_summary(fun=mean,geom='crossbar',width=.45,colour=ink)+scale_colour_manual(values=c(teal,rust))+labs(x=NULL,y='Enzyme activity (a.u.)');savefig(g,'independent')
a<-read.csv('data/simulated/assay_readings.csv');a<-aggregate(activity~preparation+condition,a,mean);p<-reshape(a,idvar='preparation',timevar='condition',direction='wide');q<-p[['activity.Compound Q']];v<-p[['activity.Vehicle']];d<-q-v;pa<-t.test(d);un<-t.test(q,v)
savefig(ggplot(a,aes(condition,activity,group=preparation))+geom_line(colour='#9CA9AA')+geom_point(aes(colour=condition),size=3)+scale_x_discrete(limits=c('Vehicle','Compound Q'))+scale_colour_manual(values=c(rust,teal))+labs(x=NULL,y='Enzyme activity (a.u.)'),'paired')
savefig(ggplot(data.frame(preparation=p$preparation,difference=d),aes(preparation,difference))+geom_hline(yintercept=0,linetype='dashed')+geom_point(size=4,colour=teal)+labs(x='Independent preparation',y='Q − vehicle (a.u.)'),'differences')
ci<-data.frame(design=c('A: unrelated cultures','B: split preparations'),estimate=mean(d),low=c(un$conf.int[1],pa$conf.int[1]),high=c(un$conf.int[2],pa$conf.int[2]))
savefig(ggplot(ci,aes(estimate,design))+geom_vline(xintercept=0,linetype='dashed')+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.15,colour=teal,linewidth=1.3)+geom_point(size=4,colour=rust)+labs(x='Q − control: mean difference and 95% CI (a.u.)',y=NULL),'design-ci')
dose<-data.frame(group=factor(rep(c('Control','Low','Medium','High'),each=8),levels=c('Control','Low','Medium','High')),value=rnorm(32,rep(c(100,96,88,76),each=8),9));write.csv(dose,'data/tests/dose.csv',row.names=FALSE)
savefig(ggplot(dose,aes(group,value))+geom_point(position=position_jitter(width=.10,seed=12),colour=teal,size=3)+stat_summary(fun=mean,geom='crossbar',width=.4,colour=rust)+labs(x='Assigned dose',y='Enzyme activity (a.u.)'),'dose')
inter<-expand.grid(treatment=factor(c('Control','Q'),levels=c('Control','Q')),genotype=c('Wild type','Knockout'),rep=1:8);inter$value<-rnorm(32,with(inter,ifelse(genotype=='Wild type',ifelse(treatment=='Q',75,100),ifelse(treatment=='Q',96,100))),8);write.csv(inter,'data/tests/interaction.csv',row.names=FALSE)
savefig(ggplot(inter,aes(treatment,value,colour=genotype,group=genotype))+stat_summary(fun=mean,geom='line',linewidth=1.2)+stat_summary(fun=mean,geom='point',size=4)+scale_colour_manual(values=c(rust,teal))+labs(x=NULL,y='Mean activity (a.u.)')+theme(legend.position='top'),'interaction')
# Explicit direct labels avoid a hidden legend in the shared plotting theme.
g<-ggplot(inter,aes(treatment,value,colour=genotype,group=genotype))+stat_summary(fun=mean,geom='line',linewidth=1.2)+stat_summary(fun=mean,geom='point',size=4)+facet_wrap(~genotype)+scale_colour_manual(values=c(rust,teal))+labs(x=NULL,y='Mean activity (a.u.)');savefig(g,'interaction')
out<-data.frame(id=1:8,value=c(91,95,97,99,101,102,105,164));write.csv(out,'data/tests/outlier.csv',row.names=FALSE);savefig(ggplot(out,aes(id,value))+geom_point(aes(colour=id==8),size=4)+scale_colour_manual(values=c(teal,rust))+labs(x='Independent culture',y='Activity (a.u.)'),'outlier')
res<-data.frame(example=c('Welch independent','Original paired','Same values independent'),estimate=c(diff(rev(wi$estimate)),mean(d),mean(d)),low=c(wi$conf.int[1],pa$conf.int[1],un$conf.int[1]),high=c(wi$conf.int[2],pa$conf.int[2],un$conf.int[2]),p=c(wi$p.value,pa$p.value,un$p.value));res$estimate[1]<-mean(ind$value[ind$group=='Q'])-mean(ind$value[ind$group=='Control']);write.csv(res,'data/tests/results.csv',row.names=FALSE)
fit<-lm(value~treatment*genotype,inter);write.csv(coef(summary(fit)),'data/tests/interaction-model.csv')
# Independent arithmetic checks for the reported mean/SE and paired equivalence.
se<-sqrt(var(ind$value[9:16])/8+var(ind$value[1:8])/8);stopifnot(abs(unname(wi$statistic)-res$estimate[1]/se)<1e-10,abs(t.test(q,v,paired=TRUE)$p.value-pa$p.value)<1e-12,all(res$low<res$estimate),all(res$estimate<res$high))
write.csv(ci,'data/tests/design-ci.csv',row.names=FALSE);print(res);print(coef(summary(fit)))
